#!/usr/bin/env bash

rlwrap sbcl --noinform --eval "(setf *read-default-float-format* 'double-float)" --eval "(require 'sb-aclrepl)" --eval "(setf sb-aclrepl:*prompt* \"~:[~3*~;[~:*~D~:[~;~:*:~D~]~:[~;i~]~:[~;c~]] ~]~A(~D)λ> \")" "$@"
