#!/usr/bin/env bash

# This script, "ftc" (Files That Contain) prints all the files that contain
# a particular string.

# Owain Kenway

if [ "$#" -ge 1 ] && [ "$#" -le 2 ] 
then
  grep -Rsl "$1" ${2:-.}/*
else
  echo "USAGE: ftc PATTERN [DIRECTORY]"
  exit 1
fi
