#!/usr/bin/env bash

# This script, "ftc" (Files That Contain) prints all the files that contain
# a particular string.

# Owain Kenway

ftcdir="."
ftcterm=""

if [ "$#" -eq 1 ]
then
  ftcterm=$1
elif [ "$#" -eq 2 ]
then
  ftcterm=$1
  ftcdir=$2
else
  echo "USAGE: ftc PATTERN [DIRECTORY]"
  exit 1
fi

for a in `find $ftcdir`
do
  grep -Hs "$ftcterm" $a
done
